#!/bin/bash

COMMIT_MSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //') 
  DESCRIPTION=$(git config branch."$NAME".description)

  if [ -n "$NAME" ]
  then
    echo "$(cat $COMMIT_MSG) | on [$NAME]" > $COMMIT_MSG
  fi

  if [ -n "$DESCRIPTION" ]
  then
     echo "" >> $COMMIT_MSG
     echo $DESCRIPTION >> $COMMIT_MSG
  fi 
}

addBranchName