#!/bin/bash

COMMIT_MSG=$1

addBranchName() {
  NAME=$(git branch | grep '*' | sed 's/* //') 
  DESCRIPTION=$(git config branch."$NAME".description)

  if [ -n "$NAME" ]
  then
    echo "$(cat $COMMIT_MSG) BY [$NAME]" > $COMMIT_MSG
  fi

  if [ -n "$DESCRIPTION" ]
  then
     echo "" >> $COMMIT_MSG
     echo $DESCRIPTION >> $COMMIT_MSG
  fi 
}

MERGE=$(cat $COMMIT_MSG|grep -i 'merge'|wc -l)

if [ $MERGE -eq 0 ] ; then
  addBranchName
fi